image: Visual Studio 2017

artifacts:
    - path: '**\*.sln'

environment:
  martix:
    -solution_path: path


before_build:
  - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%